# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hvac-bemol-monitor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: hvacbemolregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_44A1804237F34A38B5D28BD4C22F924E }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_69F9E37F945246B7B4504D38233E5A3E }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hvacbemolregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_44A1804237F34A38B5D28BD4C22F924E }}/hvac-backend:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_601DFA9965B94E158D3DB6581B196D55 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BFB8FD7401F4E27A7027BC25CE504B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_32D94867F3F542CE94571C1C97BFBEE3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hvac-bemol-monitor'
          slot-name: 'Production'
          images: 'hvacbemolregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_44A1804237F34A38B5D28BD4C22F924E }}/hvac-backend:${{ github.sha }}'
          