# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hvac-bemol-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci --silent
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: hvacbemolregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_4D7B1E657B924DDA88F0067C766C8365 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_12C879E2F4504D8AB2F7161340DB5B4D }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: hvacbemolregistry.azurecr.io/hvac-frontend:${{ github.sha }}
          file: ./frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_755BA6542B26421D940266679D0CDA12 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8D83E8643FEF4962B3E764D1EEE6D979 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_299C3C7E00FD4BE88D7F3C4B9D8326B6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hvac-bemol-frontend'
          slot-name: 'Production'
          images: 'hvacbemolregistry.azurecr.io/hvac-frontend:${{ github.sha }}'
          